### ISSUE TITLE
Nierozumiały tekst

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#1]
@bczernecki @aglogowski Chcę pobrać tylko dane z części z dwóch miesięcy. Dlaczego dostaję komunikat o "2019 05"? Może lepiej ten komunikat w ogóle usunąć?

``` r
library(climate)

x <- meteo_ogimet(interval = "daily", date = c("2019-06-01", "2019-07-08"),
                  station = 12330, coords = TRUE, precip_split = TRUE)
#> [1] 12330
#> 2019 07 
#> 2019 06 
#> 2019 05
```

<sup>Created on 2019-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bczernecki** [comment]
Jak już to dodałbym ... i opcjonalnie verbose = TRUE
Ten fragment jest ultra przydatny przy debugowaniu, bo liczenie doby meteorologicznej odbywa się na zasadzie 06-06 UTC albo 12-12 a czasem 18-18, czyli dla statów z 1. stycznia przykładowo musisz pobrać też 31.12.. Stąd też jest to tak dziwnie zrobione a liczba pobranych danych jest praktycznie taka sama.

**Comment by aglogowski** [comment]
Nie będziemy mogli kontrolować ile pobraliśmy (to zawsze jakaś informacja dla użytkownika)
Można by było usunąć -1 w tej części 
` dates <-  seq.Date(min(as.Date(date)), max(as.Date(date)), by="1 month") -1 
  dates <-  unique(c(dates, as.Date(max(date))))`
oraz w linku pobierać nie 30 dni tylko 32 (tu przy okazji znalazłem błąd wcześniej prze miesiącach mających 31 nie pobieraliśmy pierwszego dnia tego miesiąca)
Wtedy wynik byłby taki 
`[1] 12330
2019 07 
2019 07 
2019 06 `
Domyślnie funkcja pobiera zawsze 30 dni, więc jak chcemy pobrać coś od środka to najprościej do zduplikować i usunąć. 

Co myślicie o takim rozwiązaniu ?

**Comment by Nowosad** [comment]
@bczernecki do debugowania jak najbardziej jest to przydatne. Dlaczego można to zakomentować i tylko odkomentować na potrzeby debugowania. Zwykły użytkownik nie musi tego widzieć (szczególnie, że nie wie dlaczego widzi jeden miesiąc za dużo). 
@aglogowski nie znam na tyle wnętrzności funkcji. Pewnie @bczernecki więcej tutaj odpowie.

**Comment by aglogowski** [comment]
@bczernecki 
Jakby co to nie mam dostępu do edycji tej paczki. Nie wiem czy celowo czy przypadkowo:
`remote: Permission to bczernecki/climate.git denied to aglogowski.
fatal: unable to access 'https://github.com/bczernecki/climate.git/': The requested URL returned error: 403`

**Comment by bczernecki** [comment]
> @bczernecki
> Jakby co to nie mam dostępu do edycji tej paczki. Nie wiem czy celowo czy przypadkowo:
> `remote: Permission to bczernecki/climate.git denied to aglogowski. fatal: unable to access 'https://github.com/bczernecki/climate.git/': The requested URL returned error: 403`

Właśnie Ciebie dodałem

**Comment by aglogowski** [comment]
> 
> 
> > @bczernecki
> > Jakby co to nie mam dostępu do edycji tej paczki. Nie wiem czy celowo czy przypadkowo:
> > `remote: Permission to bczernecki/climate.git denied to aglogowski. fatal: unable to access 'https://github.com/bczernecki/climate.git/': The requested URL returned error: 403`
> 
> Właśnie Ciebie dodałem

To potrzeba czasu ? Ciągle mam ten sam error

**Comment by bczernecki** [comment]
@Nowosad - wrzucilem roboczo progressbar ktory dodaje informacje o pobieraniu:
 ```
# adding progress bar if at least 3 iterations are needed
    if(length(dates) >=3 ) pb <- txtProgressBar(min = 0, max = length(dates), style = 3)
 ...
# update progressbar:
      if(length(dates) >=3 ) setTxtProgressBar(pb, abs(length(dates) - i))
      
```   

Roboczo wrzucone jest do ogimet_daily.R -> jesli bedzie aprobata -> dodac do wszystkich funkcji
