### ISSUE TITLE
ogimet_hourly_bp issue for Africa

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#101]
HI, i'm tryimg t use climate package. so i want to download data from Mozambique station it is crushing and europe and america, but when i try to do the same for africa its crushing. I tried to 67341. 

[100%] Downloaded 3306 bytes...                                           |  25%
/tmp/Rtmp6KjyIu/file367439c7392d
Warning message:
In ogimet_hourly_bp(date = date, coords = coords, station = station,  :
  Wrong station ID: 67341 You can check station ID at https://ogimet.com/display_stations.php?lang=en&tipo=AND&isyn=&oaci=&nombre=&estado=&Send=Send

_Originally posted by @hicardoso in https://github.com/bczernecki/climate/issues/92#issuecomment-2451674336_

**Comment by Nowosad** [comment]
@hicardoso -- I moved your problem into a new issue: it is generally better to add a new ones instead of writing on existing ones related to some other problems.

**Comment by bczernecki** [comment]
Thanks @hicardoso for the feedback. 
I have just spotted wrong logic in the ogimet_hourly() function that may have impact in some cases. 
I have just corrected that in a branch that is being prepared for upcoming release on CRAN, but you may also check it out by installing it from "99-hydro2023-fix" branch, i.e.

```
library(remotes)
install_github("bczernecki/climate@99-hydro2023-fix")
```
