### ISSUE TITLE
nearest_stations_ogimet returns unexpected number of points

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#11]
```r
library(climate)

x <- nearest_stations_ogimet(country = "United+Kingdom", point = c(10, 50), add_map = FALSE, numbers_station = 10)
nrow(x)
#> [1] 140
```
Powyżej podałem, że chcę 10 stacji, a dostałem 140....

PS Nie wiem, czy argument `numbers_station` to najlepsza nazwa. Może `no_of_stations`?

**Comment by Nowosad** [comment]
Podobnie  argument `point` nie ma znaczenia:

```r
x <- nearest_stations_ogimet(country = "United+Kingdom", point = c(-10, -50), add_map = TRUE, numbers_station = 10)
```

**Comment by aglogowski** [comment]
Poprawione

**Comment by Nowosad** [comment]
OK!

**Comment by Nowosad** [comment]
@aglogowski jeszcze wracam do drugiego tematu:
Nie wiem, czy argument `numbers_station` to najlepsza nazwa. Może `no_of_stations`?

**Comment by aglogowski** [comment]
DONE można zamknąć

**Comment by Nowosad** [comment]
super
