### ISSUE TITLE
nearest_stations_ogimet API

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#12]
Poprawcie mnie jeżeli się mylę, ale w tej funkcji powinno być do wyboru `country` lub `point` (inaczej mówiąc (1) tylko country, (2) tylko point, (3) oba) . Co jeżeli podam "Poland", ale współrzędne punktu w Chinach? Albo chcę 50 najbliższych stacji do punktu, który jest na granicy dwóch krajów a podałem tylko jeden?

**Comment by aglogowski** [comment]
W tej funkcji musi być podany `country` **i**  `point`. Wynikiem mają być najbliższe stacje dla kraju do wskazanego punktu. Czyli jak podasz punkt w Chinach i wskażesz Polskę to dostaniesz najbliższą stację polską dla punktu w chinach. Nawiązując do drugiej części pytania rozbudowałem już funkcje o obsługę wielu krajów i to samo chyba można też zrobić dla funkcji `stations_ogimet.R`

Przykład jak to teraz działa :
nearest_stations_ogimet(country = c("United+Kingdom","Poland"), point = c(0,0), add_map = TRUE, numbers_station = 150)

Chyba można zamknąć
