### ISSUE TITLE
Better error message for nearest_stations_ogimet

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#13]
`nearest_stations_ogimet` powinien dawać bardziej informacyjny error przy błędnie podanym kraju. Powinien też sprawdzać długość argumentów wejściowych.

```r
library(climate)

x <- nearest_stations_ogimet(country = "Pland", point = c(10, 50), add_map = TRUE, numbers_station = 10)
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Error in plot.window(...): need finite 'xlim' values
```

**Comment by aglogowski** [comment]
Dodałem warunki i rozszerzyłem rysowanie mapy, żeby sprawdzał granice również dla punktu. Jak znajdę sposób na uzyskanie wszystkich stacji na ogimecie to można ulepszyć jeszcze odsyłacz do poprawy nazwy stacji. Na razie komentarz odsyła tylko linku gdzie można sobie sprawdzić kraje i stacje. 
@Nowosad 
Daj znać czy temat jest zamknięty

**Comment by Nowosad** [comment]
OK!
