### ISSUE TITLE
Error mesage for stations_ogimet

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#14]
W przypadku podania nieistniejącego kraju nie pojawia się error. Tutaj powinien być error, że ta nazwa nie istnieje i jak znaleźć prawidłową. Powinno być też sprawdzenie czy długość argumentu jest większa niż 1.

```r
library(climate)

x <- stations_ogimet(country = "Unitd+Kingdom", date = Sys.Date(),
                     add_map = FALSE)
```

**Comment by aglogowski** [comment]
Umie ktoś z was tak na szybko wydobyć z tego linku tą tabelkę ? 
Albo może już macie gdzieś jakąś?
Z tego można było by uzyskać bazę stacji po której można byłoby zrobić warunek, że stacja faktycznie nie istnieje. 

https://ogimet.com/display_stations.php?lang=en&tipo=AND&isyn=&oaci=&nombre=&estado=&Send=Send

**Comment by aglogowski** [comment]
To samo jak przy **Better error message for nearest_stations_ogimet #13** uważam, że można zamknąć temat

**Comment by Nowosad** [comment]
OK
