### ISSUE TITLE
Kod użyty w artykule

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#15]
Stabilna wersja tego kodu powinna być gdzieś w plikach pakietu. Np. w folderze `data-raw`: `01-example.R`, etc.

**Comment by aglogowski** [comment]
Pliki dodane temat chyba do zamknięcia

**Comment by Nowosad** [comment]
Super @aglogowski !
Ja jeszcze trochę wyczyściłem ten kod i zaktualizowałem go w tekście. Teraz wygląda to już ok.
