### ISSUE TITLE
Wygaszanie imgw

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#16]
https://github.com/bczernecki/imgw - tutaj dobrze byłoby zmienić nagłówek na prawdziwy (pobiera tylko imgw), albo jeszcze lepiej - informację o pakiecie climate.

**Comment by Nowosad** [comment]
Inny pomysł - można stronę imgw przerobić na język polski i tylko po angielsku dać zdanie o pakiecie climate...?

**Comment by aglogowski** [comment]
Czyli były by dwie strony tylko z jednej byłby odnośnik do drugiej ?

**Comment by Nowosad** [comment]
Plan jest taki, że dla pakietu imgw będzie tylko README na GitHubie (PL czy ANG - kwestia dyskusji). Dla pakietu climate będzie strona www.
