### ISSUE TITLE
meteo_shortening_imgw nie działa

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#19]
```r
library(climate)
monthly <- meteo_imgw("monthly", rank = "climate", year = 1969)
abbr <- meteo_shortening_imgw(data = monthly, col_names = "full", remove_duplicates = TRUE)

colnames(monthly)
colnames(abbr)
```

**Comment by aglogowski** [comment]
To jest zrobione jako Auxiliary function. Działa wewnątrz meteo_imgw
`library(climate)
monthly <- meteo_imgw("monthly", rank = "climate", year = 1969, col_names = "full")`

Chyba nie ma sensu przerabiać tego jako funkcja zewnętrzna bo to pasuje tylko do jendej cześci danych. Najlepiej byłoby chyba zmienić `@return  Auxiliary function to converte column names as abbrev, full or polish description`

**Comment by Nowosad** [comment]
usunąłem @export z tych funkcji - może to wystarczy
