### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#2]
PRogress bar kończy działanie na 67% (nie ma 100%). 
Dodatkowo to issue jest otwarte, żeby dodać progress bar do innych funkcji.

``` r
library(climate)
y <-  2018
x <- meteo_ogimet(interval = "daily", date = c("2019-06-01", "2019-07-08"),
                  station = 12330, coords = FALSE)
#> [1] 12330
#> 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |======================                                           |  33%
  |                                                                       
  |===========================================                      |  67%
```

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aglogowski** [comment]
Myślicie, że te progress bary powinny być również w tych funkcjach imgw ??

**Comment by aglogowski** [comment]
Dodawanie progress barów dla danych imgw nie ma sensu bo tam plotuje sie status pobieranego pliku więc ten progres bar i tak będzie się bez przerwy gubił, jak to przeczytacie to zadecydujcie. Jakby co progress bary są dodane do funkcji ogimet. Można zamknąć issue
