### ISSUE TITLE
Problem z pobraniem danych hydrologicznych.

### ISSUE THREAD

**Issue by MarFor9** [bczernecki/climate#22]
Błąd który zgłaszam dotyczy funckji "hydro_imgw". Gdy używam poniższego kodu:
df = hydro_imgw(interval = 'daily', year=1984,  station = "CHARZYKOWY")
to otrzymuję dane tylko dla grudnia. Inne miesiące są pobierane ale są nadpisywane.

**Comment by aglogowski** [comment]
Błąd ten nie występuje w aktualnej wersji paczki.
![obrazek](https://user-images.githubusercontent.com/40592724/72517867-6c15d580-3854-11ea-9e06-c24f81349201.png)

W celu zainstalowania/aktualizacji nowej wersji proszę o wpisanie komendy:
`library(remotes)
install_github("bczernecki/climate")
library(climate)`
Następnie spróbować uruchomić ponownie kod: 
`df = hydro_imgw(interval = 'daily', year=1984, station = "CHARZYKOWY")`

Jeżeli po przeprowadzeniu tej czynności dalej dane nie będą poprawne prosimy o informacje na temat:
- wersji R
- systemu operacyjnego

**Comment by MarFor9** [comment]
Dziękuję za pomoc. Wszystko działa ; ) 
            
          
     
      
       
        Dnia 16 stycznia 2020 11:41 Arkadiusz Głogowski &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Błąd ten nie występuje w aktualnej wersji paczki.  
 user-images.githubusercontent.com 
 W celu zainstalowania/aktualizacji nowej wersji proszę o wpisanie komendy:  
 library(remotes) install_github(&#34;bczernecki/cli library(climate)  
Następnie spróbować uruchomić ponownie kod:  
 df = hydro_imgw(interval = &#39;daily&#39;, year=1984, station = &#34;CHARZYKOWY&#34;) 
 Jeżeli po przeprowadzeniu tej czynności dalej dane nie będą poprawne prosimy o informacje na temat: 
 
 wersji R 
 systemu operacyjnego
