### ISSUE TITLE
Błąd przy pobieraniu danych dla stacji ID 12146

### ISSUE THREAD

**Issue by krzychusikorski** [bczernecki/climate#24]
Przykład wywołania błędu: 

```r
klimat <- meteo_ogimet(interval = "daily", 
                       date = c("2010-01-01", "2010-12-31"),
                       station = '12146', 
                       coords = TRUE)
```

**Comment by aglogowski** [comment]
Proszę przeinstalować paczkę i spróbować wywołać komendę jeszcze raz
przeinstalowanie wykonać przy pomocy :
`library(remotes)`
`install_github("bczernecki/climate")`

W razie dalszych problemów proszę pisać dalej

**Comment by bczernecki** [comment]
Update wysłany na cran. Powinien być widoczny w ciągu tygodnia
