### ISSUE TITLE
Winieta

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#27]
@aglogowski co się stało z https://github.com/bczernecki/climate/blob/master/vignettes/getstarted.Rmd?

W skrócie - to nie przejdzie na CRAN. Vignettes na CRANie muszą używać pakietów, które są wymienione w Suggest...

**Comment by aglogowski** [comment]
Zrobiłem examples trochę na podstawie artykułu. Nie wiedziałem, że ma byś z pakietów z suggested.
W takim razie już poprawiam.

**Comment by Nowosad** [comment]
Jak chcesz mieć taką winietę z przykładami z artykułu to lepiej ją dodać do `climate/vignettes/articles/`. Tamte winitety nie są budowane na CRANie. 
Winieta na CRAN powinna być jak najprotsza moim zdaniem (żeby uniknąć problemów z aktualizowaniem pakietu)

**Comment by aglogowski** [comment]
@Nowosad Możesz zobaczyć czy teraz jest dobrze ??

**Comment by Nowosad** [comment]
Wyczyściłem jeszcze trochę i wygląda ok.
Dzięki!
