### ISSUE TITLE
Add more CO2 sites

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#29]
Where can we find possible data sources?

**Comment by jens-daniel-mueller** [comment]
I think for atmospheric CO2 data the ICOS data portal might be a good start:
https://www.icos-cp.eu/data-services/about-data-portal

ICOS integrates many CO2 observatories for both atmosphere and ocean.
However, I never tried to access data directly through R. Would be great, if you/we could implement this!

Also, I'm not quite sure to which degree you want to extend the data access through the climate package. If ocean CO2 observations are of interest, I'm happy to guide you to some more relevant data portals.
Cheers!

**Comment by bczernecki** [comment]
We haven't got any feedback from the ICOS project. Closing for now with an option to re-open when needed.
