### ISSUE TITLE
CRAN problems

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#44]
@bczernecki - problem z CRANem może wynikać z innej małej rzeczy niż podejrzewaliśmy wcześniej. Zobacz linie https://github.com/bczernecki/climate/blob/master/R/test_url.R#L43 oraz https://github.com/bczernecki/climate/blob/169083224be5c4ae5cfb1aa01765bd869eb6af2e/R/test_url.R#L56. Tam stosujesz `stop()`. A `stop()` wywołuje error, podczas gdy error nie powinien się tam pojawić - "(...) should fail gracefully with an informative message if the resource is not available or has changed (and not give a check warning nor error)."

**Comment by Nowosad** [comment]
Przykładowo - tutaj nie ma stopów - https://community.rstudio.com/t/internet-resources-should-fail-gracefully/49199/12

**Comment by bczernecki** [comment]
Fixed in https://github.com/bczernecki/climate/pull/45
