### ISSUE TITLE
area

### ISSUE THREAD

**Issue by fipoucat** [bczernecki/climate#47]
d display Hi there,

Again thank for the climate package. My question is how to retrieve weather data for an area and display at the same time countries boundary within the area.
I am trying it on an area covering Senegal and Gambia, West Mali,South Mauritania and wonder if it is possible to add many countries rather than one by one?
Hope my explanation clear?

Thanks

**Comment by Nowosad** [comment]
The **climate** package does not offer an option for downloading data based on the provided area (yet). We want to add this feature, but it will not happen in the near future due to other responsibilities.

That being said - we would welcome any code contribution in this direction.
