### ISSUE TITLE
A "no valid data found in the database" returns error

### ISSUE THREAD

**Issue by devisdevis** [bczernecki/climate#48]
Hello,

I am trying to use SYNOP data over a whole region and would like to get the OGIMET SYNOP data. I always encounter an error and would like to get this solved (image below from Rstudio environment and the Ogimet station at the particular date). 
I checked, this error comes when there is no valid data found in the database for the station at a specific date.
How to go about this. If there is no data at all, the response could show "**NA**" as not available for "ALL" the parameters.

Thanks for your help

![image](https://user-images.githubusercontent.com/20596326/100029529-6cbeb700-2de9-11eb-9a62-e2fff7b12084.png)

![image2](https://user-images.githubusercontent.com/20596326/100029545-747e5b80-2de9-11eb-8def-5455edeb62ae.png)

**Comment by bczernecki** [comment]
This should be fixed now in Dev branch (#51 ). It will be fixed on CRAN with next release
