### ISSUE TITLE
Brak dostępu do hosta dane.imgw.pl

### ISSUE THREAD

**Issue by Jam3791** [bczernecki/climate#49]
Przy próbie uruchomienia przykładowego polecenia (wersja climate = 0.9.8):
library(climate)
dane=meteo_imgw(interval = "hourly", year = 2015, station="WROCŁAW")

pojawia się komunikat:

[1] "https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/terminowe/synop/s_t_format.txt"
Could not resolve host: dane.imgw.pl
Błąd w poleceniu 'file(con, "r")':nie można otworzyć połączenia

Obecnie dane meteo i hydro są chyba pod innym adresem.

Dla powyższego przykładu znalazłem dane pod adresem:
https://danepubliczne.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/terminowe/synop/s_t_format.txt

**Comment by Nowosad** [comment]
Sprawdziłem na dwóch komputerach i bez problemu jestem w stanie te dane pobrać używając pakietu:

![2020-11-28_08-17](https://user-images.githubusercontent.com/3457131/100496164-48990800-3152-11eb-9182-3139e29623f1.png)

@Jam3791 możesz jeszcze raz sprawdzić? Może to był chwilowy problem z internetem?

**Comment by Jam3791** [comment]
Być może - ale inne strony wczytywały się bez problemu. Różne przeglądarki (Firefox, Opera, Chrome) nie odnajdywały strony https://dane.imgw.pl. Google w wyszukiwaniach gdy zapodam dane.imgw.pl podaje danepubliczne.imgw.pl (testowane na różnych komputerach z różnych lokalizacji - nawet inni dostawcy internetu).
Polecenie ping dane.imgw.pl daje informacje o braku hosta. Ping na danepubliczne.imgw.pl działa bez problemu.
Natomiast na smartfonie (przeglądarka Chrome) strona https://dane.imgw.pl/ uruchamia się, ale wybór dowolnej grupy z danymi przekierowuje na https://danepubliczne.imgw.pl/
Pobieranie danych przez package "climate" działa jeśli podepnę komputer przez sieć komórkową. Jakoś dam sobie zatem radę z pobieraniem.

Pytanie jak długo będzie istniało przekierowanie z dane.imgw.pl na danepubliczne.imgw.pl - może jednak uaktualnić adres strony z danymi w paczce "climate"?

**Comment by Nowosad** [comment]
@

**Comment by bczernecki** [comment]
Rozwiązane w gałęzi `dev`, która będzie mergowana do `master`a przy kolejnym updacie na CRANie
