### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#5]
Zbiory danych (i w efekcie ich odniesienie się w funkcjach) muszą być zaktualizowane. Np. `meteo_stations` teraz powinno nazywać się `meteo_stations_imgw`, etc:

- `meteo_stations`
- `meteo_metadata`
- `meteo_shortening`
- `meteo_abbrev` ??
- `hydro_stations`
- `hydro_shortening`
- `hydro_metadata`
- `hydro_abbrev` ??
- `clean_metadata_meteo`
- `clean_metadata_hydro`

**Comment by Nowosad** [comment]
A później ich nazwy w README/winietach.

**Comment by aglogowski** [comment]
Powinniśmy się trzymać też jednej konwencji w kolejności np. dla ogimetu mamy:
`ogimet_stations`
więc dla imgw powinno być 
`imgw_meteo_stations`

Czy może wogóle napier żeby było station a potem nazwa zbioru ?

**Comment by Nowosad** [comment]
Teraz mamy dwie konwencje: funkcje, które widzą użytkownicy `meteo_ogimet` i dane, które widzą użytkownicy `ogimet_stations`. Mi to odpowiada, ale możemy też to ujednolicić - jak uważasz, która opcja jest lepsza?

W kwestii Twojego przykładu to powinno być `ogimet_meteo_stations` i `imgw_meteo_stations`.

**Comment by aglogowski** [comment]
Funkcje takie jak :

- `meteo_metadata`

- `clean_metadata_hydro`

odnoszą się do funkcji w paczce imgw zmiana tego wymusza zmiane w paczce imgw np. `meteo_daily`) co przestaje mieć sens bo w tej paczce są tylko dane imgw więc po co je indeksować tym dopiskiem. 
Dwie propozycje: 
1.  usuwamy funkcje operacyjne takie jak `meteo_metadata` `clean_metadata_hydro` , `meteo_abbrev` itp. i zostawiamy tylko te funkcje nadrzędne, czyli w sumie będą to: 

- `hydro_stations`

- `meteo_stations`

- `meteo_imgw`

- `hydro_imgw`

- `meteo_sounding`
zmieniamy im nazwy i pozostawiamy odniesienie do imgw

2. Pozbywamy się odniesienia imgw i wrzucamy dosłownie wszystko do climate i zmieniamy wszystko jak leci.

**Comment by aglogowski** [comment]
![przykład](https://user-images.githubusercontent.com/40592724/67848349-c2e8fa00-fb04-11e9-89f8-42c8b7c66b5c.png)

**Comment by Nowosad** [comment]
Bartek, ja myślę odwrotnie. Dopiski z "ogimet" czy "wyoming" mają duży plus - pozwalają na mniej bolesne zmiany (e.g., dodanie innych źródeł danych) w przyszłości. Jak zrobisz tylko `sounding` teraz a za rok pojawi się jakaś inna strona z `sounding`, którą będziesz chciał dodać to będziesz miał dwie funkcje - stary `sounding` i nowy `sounding_nowastrona`. Ja bym sugerował, żeby od początku ten pakiet miał wbudowane miejsce na zmiany/dodatki.

**Comment by Nowosad** [comment]
@aglogowski funkcje do pobierania danych powinny zaczynać się od `meteo_`, `hydro_`, `sounding_`, a nie od dostawcy danych. Ludzi częściej interesuje co chcą pobrać, a nie od kogo - w ten sposób ławiej jest te funkcje znaleźć poprzez autocompletion niż zgadywać jak został opisany (i czy istnieje) dany dostawca danych.

**Comment by aglogowski** [comment]
@Nowosad oki zmiany w tekście można szybko poprawić a chciałem coś zrobić żeby dzisiaj było mniej nawet kosztem robienia czegoś dwa razy :D

**Comment by aglogowski** [comment]
Czy generalnie czy w tej burzliwej dyskusji ustaliliśmy i wszyscy się zgadzają, że ma być rodzaj (meteo_, hydro_, sounding)_ a potem nazwa repo (ogimet,wyoming,imgw) czy nie? bo wyczuwam tutaj dużą rozbieżność zdań.

**Comment by bczernecki** [comment]
Tak, zostajemy przy konwencji zaproponowanej przez @Nowosad , czyli `meteo_`, `hydro_`, `sounding_wyoming`

**Comment by aglogowski** [comment]
W takim razie, ja nie wiem jak to zrobić zeby było poprawnie od strony organizacyjnej więc prosze przyjżeć się funkcji `meteo_stations` i ` hydro_stations` aby na końcu miały dopisek `_imgw` bo one są jakoś tak po profesorsku zaczytane i ja napewno coś zepsuje

**Comment by Nowosad** [comment]
Myślę, że nazwy obiektów powinny być teraz okej (ale oczywiście warto wszystko przejrzeć).
