### ISSUE TITLE
Problem with meteo_imgw function

### ISSUE THREAD

**Issue by pdjakow** [bczernecki/climate#55]
Something is wrong with meteo_imgw function for monthly climate data:

df <- meteo_imgw("monthly", year = 1961:2020, coords = TRUE, rank="climate")

throws an exception:
Błąd w poleceniu 'fix.by(by.x, x)':'by' must specify uniquely valid columns

R version: 4.0.4

**Comment by aglogowski** [comment]
Ja ten błąd poprawiłem już na dev

śr., 31 mar 2021, 11:51 użytkownik pdjakow ***@***.***>
napisał:

**Comment by bczernecki** [comment]
Changes from `dev` merged to `master` (climate ver. 1.0.0).
