### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#6]
Trzeba się określić w kwestii strony internetowej. Czy imgw.ml ma być tylko dla imgw, czy też dla climate? Jeżeli to drugie to lepiej tutaj przenieść winiety, etc.

**Comment by aglogowski** [comment]
Ja nie wiem jak to działa dokładnie z zakładaniem stron itp. ale czy zrobienie kopi dla climate nie jest czasem najprostsze i klarowne zarazem ?

**Comment by bczernecki** [comment]
Proponuję zrobić climate.ml i przenieść tam wszystko w formie połączonej. Utrzymywanie dwóch projektów na dłuższą metę nie ma sensu

**Comment by Nowosad** [comment]
W pełni się zgadzam, że powinniśmy skupić się tylko na jednej stronie.

rclimate.ml jest ok.
