### ISSUE TITLE
Suggestions to `nearest_stations_imgw()`

### ISSUE THREAD

**Issue by kadyb** [bczernecki/climate#61]
1. `nearest_stations_imgw()` returns `distance [km]` column. To make a selection, we have to use grave accents. Maybe it would be better and easier to change the column name to `distance` and record the returned units in the documentation?

```r
library("climate")

data(imgw_hydro_stations)
imgw_hydro_stations = imgw_hydro_stations[imgw_hydro_stations$id == 154170050, ]
coords = c(imgw_hydro_stations$X, imgw_hydro_stations$Y)
st = nearest_stations_imgw(type = "meteo", rank = "synop", point = coords,
                           no_of_stations = 1, add_map = FALSE)
st$`distance [km]` # column selection

make.names(colnames(st)[5])
#> "distance..km."
```

2. Since the argument `add_map = TRUE` requires additional packages, maybe it would be better to change it to `FALSE`? This will avoid errors if packages are not installed.

**Comment by bczernecki** [comment]
Ad.1 .Units are now added as attributes:

<img width="536" alt="obraz" src="https://user-images.githubusercontent.com/8086055/171066527-7be2e4da-09db-4161-a03b-8131314c3455.png">

Ad.2. `add_map = FALSE` by default in the function.
