### ISSUE TITLE
IMGW hydrological data has different number of columns 

### ISSUE THREAD

**Issue by kadyb** [bczernecki/climate#62]
Hydrological data for the current year doesn't have the `Przepływ [m^3/s]` column until the end of the verification. 

```r
library("climate")

test = hydro_imgw_daily(year = 2019:2020)

#> Error in names(x) <- value : 
#>   'names' attribute [10] must be the same length as the vector [9]
```

I think a good idea would be to check if the data consists of 9 columns, if so we can create a 10th column with NAs and then insert it in the 8th position. Something like this:

```r
if (ncol(data) == 9) {
  flow_NA = rep_len(NA, nrow(data))
  data = cbind(data, flow_NA)
  data = data[, c(1:7, 10, 8:9)]
}
```

**Comment by bczernecki** [comment]
Thanks Krzysztof for spotting this issue!
I know that @aglogowski might be quite busy recently so I fixed it accordingly in the `dev` branch. Fixed version will be available on CRAN once the major release will be ready

**Comment by kadyb** [comment]
Thanks!
