### ISSUE TITLE
Error in another wyoming url

### ISSUE THREAD

**Issue by MengXin001** [bczernecki/climate#63]
I changed Wyoming data url in `sounding_wyoming.R`.  
` url = paste0("http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=", yy, "-", mm, "-", dd, "%20", hh, ":00:00&id=",wmo_id, "&type=TEXT:LIST")`  into  `url = paste0("http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=", yy, "-", mm, "-", dd, "%20", hh, ":00:00&id=",wmo_id, "&type=TEXT:LIST")`.  
  
I changed it because this link supports data in more China region. I think the content of these two pages in the main data section of `<PRE></PRE>` is the same. But is wrong when i test it.  
  
`profile <- sounding_wyoming(wmo_id = 45004, yy = 2021, mm = 07, dd = 16, hh = 00)`
`[1] "http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=2021-07-16%2000:00:00&id=45004&type=TEXT:LIST"`
`Downloaded 164999 bytes...C:\Users\ADMINI~1\AppData\Local\Temp\2\Rtmp6F2IPE\file28d43e8110ae`
`Error in if (n == 0L) break : missing value where TRUE/FALSE needed`.  
  
Where should I improve? Thanks in advance. 
  
[Links1](http://weather.uwyo.edu/cgi-bin/bufrraob.py?datetime=2021-07-17%2000:00:00&id=45004&type=TEXT:LIST) (Which I want to use)
[Links2](http://weather.uwyo.edu/cgi-bin/sounding?region=seasia&TYPE=TEXT%3ALIST&YEAR=2021&MONTH=07&FROM=1700&TO=1700&STNM=45004) (Original)

**Comment by bczernecki** [comment]
Hi @MengXin001 

First of all thank you for using `climate` and giving us the feedback. 

I have added some improvements in the `dev` version that should handle the BUFR sounding format.
Please let me know if this piece of code works properly for you:

```
install_github("bczernecki/climate", def = "dev")
```

Then you can check these 2 examples that were added to examples section:

```
library(climate)
TEMP = sounding_wyoming(wmo_id = 45004, yy = 2021, mm = 07, dd = 17, hh = 12, min = 00)
BUFR = sounding_wyoming(wmo_id = 45004, yy = 2021, mm = 07, dd = 17, hh = 12, min = 00, bufr = TRUE)
```

The changes will be officially released once new update of **climate**  will be sent to CRAN.

Thanks!
Bartek

**Comment by MengXin001** [comment]
It works well! By the way, we also need to pay attention to that in the data of BUFR, the unit of wind speed is `m/s` rather than `kt`, and the unit conversion should be carried out when drawing the sounding.
Thank you for updating this program!

**Comment by bczernecki** [comment]
If the `bufr = TRUE` is used then it is automagically converted to knots to keep the same structure as for sounding derived from TEMP format (as described in documentation).
