### ISSUE TITLE
CRAN email

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#65]
Please correct before 2021-09-19 to safely retain your package on CRAN.
https://cran.r-project.org/web/checks/check_results_climate.html

Actual problem: https://www.stats.ox.ac.uk/pub/bdr/donttest/climate.out

```r
library(climate)
poznan = ogimet_hourly(station = 12330, coords = TRUE, precip_split = TRUE)
#> Error in `[.data.frame`(data_station, , c("TC", "TdC", "ffkmh", "Gustkmh",  : 
#>   undefined columns selected
```

(Sidenote: I can reproduce this issue on my computer)

**Comment by aglogowski** [comment]
Ja trochę już próbowałem zmienić funkcje ogimetu ale z marnym skutkiem i
nie skończyłem.
Aktualnie są na sztywno zdefiniowane nazwy kolumn i to się nie sprawdza bo
często informacje są przechowywane w podobnych nazwach ale z dodanym jednym
znakiem albo po prostu inne znaki są z wielkiej litery.
Aktualnie jestem w Grecji na wakacjach po tym całym stażu wracam 15 i będę
chciał to zmienić żeby działalo to lepiej niż do tej pory.

pt., 10 wrz 2021, 14:29 użytkownik Jakub Nowosad ***@***.***>
napisał:

**Comment by bczernecki** [comment]
Column names are now dynamically allocated/selected for `ogimet_hourly`
