### ISSUE TITLE
New error message when downloading OGIMET data

### ISSUE THREAD

**Issue by gabnagle** [bczernecki/climate#69]
I have been downloading daily data for the past 40 years for all stations in the US over the last few days. Up until today the code has been working and downloading all of the available data. I have gotten a few error messages for some stations but realized through another "issue" on github that it might mean that some of the stations only capture certain data. Starting today, every station I try to run results in an error and I have even tried to run several stations that I already have the data for and am receiving an error for them too. I am not sure what could have changed, so any insights would be greatly appreciated!

Below is an example of the line that I am running, just with different stations.

station70200 <- meteo_ogimet(date=c(Sys.Date()-15237, Sys.Date()-272), interval="daily", coords=FALSE, station=	
70200)

Here is the error message I am receiving.
Warning in ogimet_daily(date = date, coords = coords, station = station) :
  Mandatory meteorological parameters (i.e. Temperature or precipitations) are not present. 
Check content of the current URL:
https://www.ogimet.com/cgi-bin/gsynres?lang=en&ind=70200&ndays=32&ano=2004&mes=11&day=16&hora=6&ord=REV&Send=Send
Error in if ((length(test[2, !is.na(test[2, ])]) == 6 & test[2, 5] ==  : 
  argument is of length zero

**Comment by bczernecki** [comment]
Dear @gabnagle ,
As it is written in the `README` file - the `ogimet_` set of functions work only with dates after 1999 (in most cases). If you want to download earlier dataset then `meteo_noaa_hourly` is better choice.
Anyway, I tried to reproduce the error with ogimet dataset, but I wasn't able to do so. Could you specify between which dates (interval < 1-2 mths) the error occur?

**Comment by bczernecki** [comment]
Closing
