### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Laplace3210** [bczernecki/climate#72]
Dear authors,
I can't run the example code because of "No internet connection" issues like that:
![1641792476(1)](https://user-images.githubusercontent.com/50813700/148723246-bc6ad900-c217-4dcf-8214-dd770b9ab281.png)
how should I solve it?

Bests

**Comment by Nowosad** [comment]
Dear @Laplace3210, have you tried to download the link ([1]) using your web browser? Was that successful?

**Comment by bczernecki** [comment]
Closing as the error message seems to be self-explanatory

**Comment by bczernecki** [comment]
Please reinstall the package using the newest version using:

```r
library(remotes)
install_github("bczernecki/climate")
```

then try again and provide `sessionInfo()` details
