### ISSUE TITLE
Problem downloading OPAD data for 2021

### ISSUE THREAD

**Issue by Armin-RS** [bczernecki/climate#73]
Let me first thank you very much for your very useful "climate" package which I'm using to download IMGW data.

Unfortunately, I have a problem downloading daily OPAD precipitation data for 2021 which is currently available until November 2021.

I'm using this command:
 m=meteo_imgw(interval="daily", rank="precip", year=2021:2021, coords=TRUE, status=TRUE, col_names="full")

which gives me an error message like this:
[1] "https://danepubliczne.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/dobowe/opad/2021/2021_05_o.zip"
 [100%] Downloaded 63255 bytes...
/tmp/Rtmpcixfr8/file1a285c4ff5621a
Fehler in file(file, "rt", encoding = fileEncoding) :
  kann Verbindung nicht öffnen
Zusätzlich: Warnmeldungen:
1: In unzip(zipfile = temp, exdir = temp2) : Zip-Datei ist defekt
2: In file(file, "rt", encoding = fileEncoding) :
  'raw = FALSE' but '/tmp/Rtmpcixfr8/file1a285c5f1ee556/' is not a regular file
3: In file(file, "rt", encoding = fileEncoding) :
  cannot open file '/tmp/Rtmpcixfr8/file1a285c5f1ee556/': it is a directory

It claims (in German) that the ZIP file is corrupt. However, downloading the file manually, I can unzip the file without problems on my Linux machine.

getOption("unzip") gives  "/usr/bin/unzip" which is the same UNZIP I'm using on the command-line.

Do you have any advice how I can proceed ?

Thanks for your help and best regards,
Armin Rauthe-Schöch

**Comment by bczernecki** [comment]
Hi @Armin-RS 
The error message is not very informative, but I believe there's something wrong with the file for May 21'. 
I have downloaded the same file on my laptops (Mac, Linux) and the message is still the same - file is corrupted. However, it works in a browser and in system shell, so there is sth wrong actually with the way how R tries to extract this file on Linux/Unix systems. I think it might be related to the zlib library which is used by `unzip` function on non-Windows systems:

```
The internal C code uses zlib and is in particular based on the contributed minizip application in the zlib sources (from https://zlib.net/)
```

What I can recommend is to :
- (1) check the same command on Windows 
- (2) slightly more complicated - overwrite R's `unzip`:


Solution for no. 2:
```
# first - modify the default unzip:

unzip = function (zipfile, files = NULL, list = FALSE, overwrite = TRUE, 
          junkpaths = FALSE, exdir = ".", unzip = "internal", setTimes = FALSE) {
  if (identical(unzip, "internal")) {
    if (!list && !missing(exdir)) 
      dir.create(exdir, showWarnings = FALSE, recursive = TRUE)
    res <- system(paste0("/usr/bin/unzip -o ", zipfile, " -d ", exdir))
    if (list) {
      dates <- as.POSIXct(res[[3]], "%Y-%m-%d %H:%M", tz = "UTC")
      data.frame(Name = res[[1]], Length = res[[2]], Date = dates, 
                 stringsAsFactors = FALSE)
    }
    else invisible(attr(res, "extracted"))
  }
  else {
    WINDOWS <- .Platform$OS.type == "windows"
    if (!is.character(unzip) || length(unzip) != 1L || !nzchar(unzip)) 
      stop("'unzip' must be a single character string")
    zipfile <- path.expand(zipfile)
    if (list) {
      res <- if (WINDOWS) 
        system2(unzip, c("-ql", shQuote(zipfile)), stdout = TRUE)
      else system2(unzip, c("-ql", shQuote(zipfile)), stdout = TRUE, 
                   env = c("TZ=UTC"))
      l <- length(res)
      res2 <- res[-c(2, l - 1, l)]
      res3 <- gsub(" *([^ ]+) +([^ ]+) +([^ ]+) +(.*)", 
                   "\\1 \\2 \\3 \"\\4\"", res2)
      con <- textConnection(res3)
      on.exit(close(con))
      z <- read.table(con, header = TRUE, as.is = TRUE)
      dt <- paste(z$Date, z$Time)
      formats <- if (max(nchar(z$Date) > 8)) 
        c("%Y-%m-%d", "%d-%m-%Y", "%m-%d-%Y")
      else c("%m-%d-%y", "%d-%m-%y", "%y-%m-%d")
      slash <- any(grepl("/", z$Date))
      if (slash) 
        formats <- gsub("-", "/", formats, fixed = TRUE)
      formats <- paste(formats, "%H:%M")
      for (f in formats) {
        zz <- as.POSIXct(dt, tz = "UTC", format = f)
        if (all(!is.na(zz))) 
          break
      }
      z[, "Date"] <- zz
      z[c("Name", "Length", "Date")]
    }
    else {
      args <- character()
      if (junkpaths) 
        args <- c(args, "-j")
      if (overwrite) 
        args <- c(args, "-oq", shQuote(zipfile))
      else args <- c(args, "-nq", shQuote(zipfile))
      if (length(files)) 
        args <- c(args, shQuote(files))
      if (exdir != ".") 
        args <- c(args, "-d", shQuote(exdir))
      if (WINDOWS) 
        system2(unzip, args, stdout = NULL, stderr = NULL, 
                invisible = TRUE)
      else system2(unzip, args, stdout = NULL, stderr = NULL)
      invisible(NULL)
    }
  }
}

# overwrite the unzip in utils package:
assignInNamespace("unzip", unzip, ns = "utils")

# activate climate with the newer unzip command:
library(climate)
m = meteo_imgw(interval="daily", rank="precip", year=2021, 
               coords=TRUE, status=TRUE, col_names="full")
```

**Comment by Armin-RS** [comment]
Hi @bczernecki,

thank you for your very detailed reply!

I tried the same command on a Windows 10 computer and it failed with the same error message.

I also believe that there is something wrong with these files because when I extract the June 2021 on the Windows computer, it has less than 5000 lines compared to the typical 11000 of most other months.

For now, I worked around the problem by manually downloading, extracting and reformatting the 2021 precipitation files.

Is there anyone at IMGW whom I could notify about the corrupt files ?


Thanks again and have a nice weekend,
Armin

**Comment by bczernecki** [comment]
The solution that I have provided above returned over 11k rows for May 2021, so it seems to be working fine. Here's the output for all that is available so far for 2021: [2021.xlsx](https://github.com/bczernecki/climate/files/8004591/2021.xlsx)

I have never had this kind of situation before, but I think you can try to contact IMGW by official form: https://imgw.pl/kontakt/reklamacje (in Polish, but writing in English shouldn't be a problem). I can also ask some of my friends working there about contact person to address this question.

**Comment by Armin-RS** [comment]
Further investigation (with "zip -F --out fixed.zip 2021_05_o.zip") showed that the CRC checksum of the ZIP archive is wrong. That's probably why R does not want to decompress the file.

You are right, the May 2021 file has 11k rows. But the June 2021 file has only 4.7k rows which I also find a bit odd that suddenly so many stations are not reporting in June.

Anyway, as this is not a bug in the "climate" package, I will close this issue.
