### ISSUE TITLE
two suggestions for sounding_wyoming

### ISSUE THREAD

**Issue by abigmo** [bczernecki/climate#80]
In order to get all BUFR soundings it would be good to change the function with the following (some text missing in the url and the heading 0 for wmo ID):

``` 
url = paste0("http://weather.uwyo.edu/cgi-bin/bufrraob.py?src=bufr&datetime=", 
            yy, "-", mm, "-", dd, "+", hh, ":", min, ":00&id=", 
            sprintf("%05d", wmo_id), "&type=TEXT:LIST")
```

you can double check with retrieving soundings from Payerne, WMO ID: 06610

HTH,

 Alessandro

**Comment by bczernecki** [comment]
Thanks @abigmo for the very good point! 

Already tested and changed on the develop branch (https://github.com/bczernecki/climate/tree/dev). It will be available by default in the next release of the climate package.
