### ISSUE TITLE
Walter diagram with Climate

### ISSUE THREAD

**Issue by fipoucat** [bczernecki/climate#84]
I am trying to produce this diagram for my station using meteo_ogimet but looks not working with this error message:

df = meteo_ogimet(interval = 'monthly', rank='synop', year = 2000:2019, station = "61612")
Error in meteo_ogimet(interval = "monthly", rank = "synop", year = 2000:2019,  : 
  unused arguments (rank = "synop", year = 2000:2019)

Is there a way to do this?

**Comment by Nowosad** [comment]
@fipoucat check the documentation of the `meteo_ogimet` function (`?meteo_ogimet`). This function does not have `rank` and `year` arguments (there is the `date` argument, though). Also, it only allows to select `'hourly'` or `'daily'` interval.
Example of a working code:

```r
df = meteo_ogimet(interval = 'daily', date = c("2000-01-01", "2000-01-30"), station = "61612")
```
