### ISSUE TITLE
Error when trying to find the nearest meteorological stations in Spain

### ISSUE THREAD

**Issue by jbaezarh** [bczernecki/climate#88]
When I try to get the nearest meteorological station to any point in Spain, I get the following error:
`nearest_stations_ogimet(country="Spain",
                        date = Sys.Date(),
                        add_map = TRUE,
                        point = c(-5, 37),
                        no_of_stations = 100)`

> [1] "http://ogimet.com/cgi-bin/gsynres?lang=en&state=Spain&osum=no&fmt=html&ord=REV&ano=2024&mes=02&day=20&hora=06&ndays=1&Send=send"
 [100%] Downloaded 31584 bytes...
C:\Users\usuario\AppData\Local\Temp\RtmpuejQSX\file9c07d751ed
Problems with downloading data. Run function with argument allow_failure = FALSE to see more details
Warning messages:
1: In strsplit(a, "Decoded synops since") :
  unable to translate '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>Synop report summary by countries</TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Author" content="G. Ballester Valor"><meta name="r...' to a wide string
2: In strsplit(a, "Decoded synops since") : input string 1 is invalid

I hope this can be solved as soon as possible, it would help me a lot!!

**Comment by aglogowski** [comment]
Try without `date=Sys.Date()` as it works as default and maybe couse an issue?
I get a requierd map and result while running
`nearest_stations_ogimet(country = "Spain",date = add_map = T,point = c(-5,37),no_of_stations = 100)`

`> nearest_stations_ogimet(country = "Spain",add_map = T,point = c(-5,37),no_of_stations = 100)
[1] "http://ogimet.com/cgi-bin/gsynres?lang=en&state=Spain&osum=no&fmt=html&ord=REV&ano=2024&mes=02&day=21&hora=06&ndays=1&Send=send"
 [100%] Downloaded 31675 bytes...
C:\Users\arek\AppData\Local\Temp\Rtmp04JOv1\file390060514332
    wmo_id                      station_names       lon      lat  alt  distance
188  08413                         Bobadilla  -4.733348 37.01667  408  29.97585
185  08399                 Roda De Andalucía  -4.766682 37.18334  410  33.29232
205  08455                         Grazalema  -5.366674 36.75001  913  49.79085
183  08395                             Ecija  -5.083335 37.50001  130  56.87328
208  08463                          Estepona  -5.150003 36.41667   15  67.57640
210  08480                        Fuengirola  -4.616679 36.53334    9  67.75628
211  08481                               cmt  -4.466676 36.71668   54  67.75640
184  08397              Morón De La Frontera  -5.600012 37.15000   87  69.39120
212  08482               Málaga / Aeropuerto  -4.466676 36.65001    5  71.57105
209  08479                            puerto  -4.416675 36.71668   25  72.75828
186  08410              Córdoba / Aeropuerto  -4.833350 37.83335   90  95.35030
187  08412                       Doña Mencia  -4.350007 37.55001  650  95.53222
189  08414                              Loja  -4.150003 37.15000  760  96.84047
181  08391               Sevilla / San Pablo  -5.866684 37.41667   34 107.89326
202  08451 Jerez De La Frontera / Aeropuerto  -6.050001 36.75001   27 121.09938
213  08484                              faro  -3.950019 36.71668    3 122.01767
207  08458                            Tarifa  -5.583345 36.00000   32 129.89116
249  60320                             Ceuta  -5.333340 35.88335   87 130.74743
182  08392              Cazalla De La Sierra  -5.766682 37.91669  550 134.07914
206  08457              Vejer De La Frontera  -5.950019 36.23334  186 136.96759
191  08419              Granada / Aeropuerto  -3.783349 37.18334  567 138.04532
204  08453                      San Fernando  -6.200004 36.45001   30 148.10384
203  08452                      Observatorio  -6.250005 36.48334    2 151.75391
163  08346             Villanueva De Córdoba  -4.600012 38.31667  750 154.39249
192  08420              Granada / Base Aérea  -3.616679 37.13334  687 155.92332
164  08347                           Andujar  -4.050001 38.01667  202 156.11512
190  08417                              Jaén  -3.800016 37.76668  580 159.76754
159  08335                Hinojosa del Duque  -5.116669 38.48334  551 166.94013
160  08336                           Llerena  -6.016667 38.21667  655 177.89100
228  08980                     Sierra Nevada  -3.383341 37.05000 2856 181.47049
180  08384                     El Arenosillo  -6.733348 37.10000   41 194.79926
179  08383                            Huelva  -6.900018 37.26667   19 215.26511
214  08486                      club Nautico  -3.016667 36.73335    8 224.52550
162  08345                  Viso del Marqués  -3.566678 38.51668  804 234.13166
130  08271              Puebla De Don Rodrig  -4.600012 39.08333  485 238.01236
158  08333                        Don Benito  -5.866684 38.95002  273 239.42137
128  08264                 Herrera Del Duque  -5.050001 39.16667  447 243.15789
161  08337              Jerez De Los Caballe  -6.750015 38.28334  381 243.48259
195  08427                              Abla  -2.766682 37.13334  869 251.01702
165  08348                       Ciudad Real  -3.916685 38.98335  628 253.55605
193  08424                         Cruz Roja  -2.733348 37.50001  785 260.42492
216  08492                              Faro  -2.700014 36.68335    3 260.48493
157  08331                            Mérida  -6.383341 38.90002  228 263.69084
166  08351                        Valdepeñas  -3.383341 38.75001  700 267.30463
178  08381                        Isla Canel  -7.383341 37.18334    2 268.19292
167  08352                 Arroyo Del Ojanco  -2.883351 38.30001  580 278.69569
156  08330        Badajoz / Talavera La Real  -6.800016 38.86668  185 290.94583
127  08263                          Trujillo  -5.850017 39.46668  503 292.72409
129  08270              San Pablo De Los Mon  -4.350007 39.53334  917 293.43930
215  08487              Almería / Aeropuerto  -2.350007 36.83335   21 297.90773
250  60338                           Melilla  -2.950019 35.26667   47 301.19840
168  08354                     Villarrodrigo  -2.633346 38.48334  862 313.37552
126  08261                           Cáceres  -6.333340 39.46668  394 314.59687
132  08273                        Madridejos  -3.516677 39.48334  690 324.54213
135  08276                         Tomelloso  -3.000000 39.16667  662 330.82723
133  08274              Talavera De La Reina  -4.850017 39.95002  372 331.40981
123  08254              Navalmoral De La Mat  -5.566678 39.93335  269 335.19735
131  08272                            Toledo  -4.033334 39.88335  515 341.19884
196  08428                     Huercal Overa  -1.933352 37.38334  300 346.74545
122  08252                         Plasencia  -6.083335 40.03333  415 361.38355
134  08275              Quintanar De La Orde  -3.033334 39.58335  691 364.27560
125  08260             Valencia De Alcántara  -7.233338 39.40001  445 367.82438
100  08208              Sotillo De La Adrada  -4.583345 40.28334  630 371.33397
175  08365                       fuentes Del  -1.866684 38.10000  643 372.58205
121  08251                             Coria  -6.550011 40.00000  313 378.86167
194  08426                             Lorca  -1.683347 37.65001  312 379.19660
113  08229                          Aranjuez  -3.533344 40.06667  540 381.39497
99   08205                            Estaci  -5.683347 40.35001 1960 383.59959
199  08432                           Aguilas  -1.583345 37.41667   32 386.17745
102  08212                Robledo de Chavela  -4.233338 40.41667  763 392.87165
111  08224                   Madrid / Getafe  -3.716681 40.28334  620 395.51869
124  08256                      San Clemente  -2.416675 39.41667  728 396.89541
110  08223           Madrid / Cuatro Vientos  -3.783349 40.36667  690 401.63797
136  08277                          Tarancon  -3.016667 40.00000  808 403.49657
169  08355                            Hellín  -1.700014 38.53334  646 408.26412
109  08222                    Madrid, Retiro  -3.666680 40.40001  667 409.75289
101  08210                             Ávila  -4.666680 40.65001 1130 411.22334
107  08220         Madrid / C. Universitaria  -3.716681 40.45001  664 412.99151
139  08280             Albacete / Los Llanos  -1.850017 38.95002  702 415.65751
138  08279                              Obs.  -1.850017 39.00000  679 418.63633
108  08221                  Madrid / Barajas  -3.550011 40.46668  609 421.60145
105  08217                Alto De Los Leones  -4.133336 40.70001 1532 426.36522
174  08363                Parque De Bomberos  -1.366674 38.21667  265 429.89551
137  08278                  Chinchilla/Cenad  -1.650013 38.93335  880 433.95989
106  08219              Colmenar Viejo/Famet  -3.750015 40.68335 1004 436.40767
197  08429             Murcia / Alcantarilla  -1.216671 37.95002   75 437.65496
104  08215                       Navacerrada  -4.000000 40.78335 1894 439.05655
198  08430                            Murcia  -1.166670 38.00000   61 444.48038
96   08195                 Saelices El Chico  -6.583345 40.63335  680 444.67526
98   08202               Salamanca / Matacán  -5.483343 40.95002  790 446.48455
97   08201                    Salamanca-obs.  -5.650013 40.95002  775 449.13951
201  08434                        Tengegorra  -1.016667 37.60001   55 451.95845
103  08213                           Segovia  -4.116669 40.93335 1005 452.30056
112  08226                       Guadalajara  -3.133336 40.61668  721 456.63910
170  08356                             Yecla  -1.150003 38.60001  640 467.77422
171  08357                            Pinoso  -1.033334 38.38334  575 471.33382
114  08231                            Cuenca  -2.116669 40.06667  945 472.26737
77   08146                          Buitrago  -3.600012 41.00000 1026 475.48053
70   08129                        Vitigudino  -6.433342 41.00000  769 476.72984
200  08433               Murcia / San Javier  -0.800016 37.78335    4 479.35037`

**Comment by jbaezarh** [comment]
Thank you very much for your quick answer.
I tried as you said and I keep having the same error:
`nearest_stations_ogimet(country = "Spain",add_map = T,point = c(-5,37),no_of_stations = 100) `

> [1] "http://ogimet.com/cgi-bin/gsynres?lang=en&state=Spain&osum=no&fmt=html&ord=REV&ano=2024&mes=02&day=21&hora=06&ndays=1&Send=send"
>  [100%] Downloaded 31675 bytes...
> C:\Users\usuario\AppData\Local\Temp\RtmpkrZ130\file573c11ba59f3
> Problems with downloading data. Run function with argument allow_failure = FALSE to see more details
> Warning messages:
> 1: In strsplit(a, "Decoded synops since") :
>   unable to translate '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>Synop report summary by countries</TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Author" content="G. Ballester Valor"><meta name="r...' to a wide string
> 2: In strsplit(a, "Decoded synops since") : input string 1 is invalid

Then, I tried with  `allow_failure = FALSE` as it sais, and I get the same problem:
`nearest_stations_ogimet(country = "Spain",add_map = T,point = c(-5,37),no_of_stations = 100, allow_failure = FALSE) `

> [1] "http://ogimet.com/cgi-bin/gsynres?lang=en&state=Spain&osum=no&fmt=html&ord=REV&ano=2024&mes=02&day=21&hora=06&ndays=1&Send=send"
>  [100%] Downloaded 31675 bytes...
> C:\Users\usuario\AppData\Local\Temp\RtmpkrZ130\file573c22381705
> Error in `[.data.frame`(result, , 3:4) : undefined columns selected
> Además: Warning messages:
> 1: In strsplit(a, "Decoded synops since") :
>   unable to translate '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>Synop report summary by countries</TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Author" content="G. Ballester Valor"><meta name="r...' to a wide string
> 2: In strsplit(a, "Decoded synops since") : input string 1 is invalid

And when I try with any other country I get the expected map and data:

`nearest_stations_ogimet(country = "France",add_map = T,point = c(-5,37),no_of_stations = 100, allow_failure = FALSE)` 

> [1] "http://ogimet.com/cgi-bin/gsynres?lang=en&state=France&osum=no&fmt=html&ord=REV&ano=2024&mes=02&day=21&hora=06&ndays=1&Send=send"
>  [100%] Downloaded 22001 bytes...
> C:\Users\usuario\AppData\Local\Temp\RtmpkrZ130\file573c7e7b2a76
>     wmo_id          station_names       lon      lat  alt  distance
> 123  07600                 Socoa  -1.683347 43.38334   21  807.0929
> 124  07602              Biarritz  -1.533344 43.46668   75  823.2178
> 125  07603                   Dax  -1.066668 43.68335   33  870.0722
> 127  07610                   Pau  -0.400008 43.38334  188  882.7744
> 128  07621  Tarbes Ossun Lourdes   0.000000 43.18334  384  892.1834
> 126  07607        Mont-De-Marsan  -0.500010 43.90002   62  924.2456
> 104  07503            Biscarosse  -1.233338 44.41667   35  933.2903
> 103  07502                Cazaux  -1.116669 44.53334   23  950.9059
> 102  07500            Cap Ferret  -1.233338 44.61668    9  953.3518
> 130  07627             St-Girons   1.100002 43.00000  419  959.9868
> 129  07622                  Auch   0.600012 43.68335  125  978.2833
> 105  07510   Bordeaux / Merignac  -0.683347 44.81668   51 1001.8480
> 106  07524                  Agen   0.583345 44.16667   62 1019.2924
> 131  07630    Toulouse / Blagnac   1.366674 43.61668  152 1030.2256
> 109  07540             Montauban   1.366674 44.01667  108 1063.0192
> 133  07635           Carcassonne   2.283339 43.20000  132 1073.1486
> 107  07530              Bergerac   0.516677 44.81668   52 1073.4253
> 78   07314             Chassiron  -1.400008 46.03333   11 1091.0286
> 148  07747             Perpignan   2.866684 42.73335   44 1092.1526
> 149  07749              Cap Bear   3.133336 42.51668   82 1102.6420
> 88   07412                Cognac  -0.300006 45.65001   31 1104.5115
> 132  07632                  Albi   2.100002 43.90002  172 1110.8053
> 79   07316  La Rochelle Aeroport  -1.183337 46.16667   23 1114.0556
> 143  07666               Leucate   3.050001 42.91669   42 1120.8985
> 108  07535               Gourdon   1.383341 44.73335  260 1125.0575
> 76   07300            St-Sauveur  -2.316673 46.68335   32 1127.3809
> 91   07439        Brive-Souillac   1.483343 45.03333  295 1158.2272
> 77   07306      La Roche-Sur-Yon  -1.366674 46.70001   91 1162.1503
> 80   07330                 Niort  -0.400008 46.30001   61 1164.0914
> 90   07438                 Brive   1.466676 45.13334  112 1165.8150
> 56   07207              Le Talut  -3.216671 47.28334   34 1170.9771
> 134  07638          Beziers-Vias   3.350007 43.31667   17 1174.7103
> 111  07552                 Rodez   2.466676 44.40001  582 1179.4606
> 57   07217            St-Nazaire  -2.150003 47.30001    4 1199.0492
> 58   07222                Nantes  -1.600012 47.13334   27 1199.2161
> 113  07558                Millau   3.016667 44.11667  712 1202.7249
> 54   07203             Beg Melen  -3.500010 47.65001   41 1206.6894
> 135  07641                  Sete   3.683347 43.38334   80 1209.1635
> 89   07434               Limoges   1.166670 45.85002  402 1210.2200
> 110  07549              Aurillac   2.416675 44.88335  639 1214.3925
> 55   07205           Lann Bihoue  -3.433342 47.75001   49 1218.8568
> 81   07335              Poitiers   0.300006 46.58335  129 1228.6973
> 53   07201               Quimper  -4.150003 47.96669   89 1234.1159
> 136  07643           Montpellier   3.950019 43.56668    5 1245.4543
> 114  07560          Mont Aigoual   3.566678 44.11667 1567 1249.5453
> 26   07109       Lanveoc Poulmic  -4.433342 48.26667   87 1265.6809
> 112  07554                 Mende   3.450009 44.53334  932 1270.1234
> 60   07230             Beaucouze  -0.600012 47.46668   50 1273.8706
> 22   07100        Ouessant-Stiff  -5.050001 48.46668   64 1286.5351
> 27   07110                 Brest  -4.366674 48.45001   94 1286.6166
> 83   07361     Gueret St Laurent   1.950019 46.16667  365 1290.6549
> 23   07101         Ploudalmezeau  -4.650013 48.53334   40 1294.5985
> 32   07130                Rennes  -1.733348 48.06667   38 1294.6065
> 59   07228                 Marce  -0.316673 47.55001   53 1295.0640
> 24   07106           Landivisiau  -4.133336 48.51668  109 1295.7863
> 138  07646        Nimes / Garons   4.416675 43.75001   94 1299.9158
> 137  07645    Nimes / Courbessac   4.400008 43.85002   60 1304.9726
> 25   07107             Brignogan  -4.316673 48.66668    9 1311.2060
> 30   07120          Saint-Brieuc  -2.850017 48.53334  138 1316.2944
> 33   07134                 Laval  -0.733348 48.01667  101 1325.4947
> 29   07118               Lannion  -3.466676 48.75001   88 1329.4900
> 139  07647                Istres   4.916685 43.51668   25 1331.3530
> 62   07240                 Tours   0.716681 47.43334  109 1334.7871
> 93   07471                Le Puy   3.750015 45.06667  832 1335.2530
> 28   07117           Ploumanac'H  -3.466676 48.81668   55 1336.9074
> 82   07354     Chateauroux Deols   1.733348 46.86668  161 1340.2193
> 31   07125                Dinard  -2.066668 48.58335   67 1340.6367
> 92   07460      Clermont-Ferrand   3.133336 45.78335  333 1343.0761
> 116  07570               Aubenas   4.366674 44.53334  281 1348.6294
> 141  07650 Marseille / Marignane   5.200004 43.43334   21 1353.0192
> 140  07648                 Salon   5.100002 43.60001   60 1353.6806
> 115  07563               Avignon   4.900018 43.90002   38 1353.9150
> 61   07235               Le Mans   0.183337 47.93335   59 1357.5573
> 118  07579                Orange   4.850017 44.13334   60 1364.5040
> 119  07586            Carpentras   5.050001 44.06667   99 1378.4233
> 64   07247            Romorantin   1.683347 47.31667   88 1379.1562
> 117  07577            Montelimar   4.716681 44.56668   73 1381.7443
> 63   07245                 Blois   1.200004 47.66668  121 1384.2456
> 84   07374                 Vichy   3.383341 46.16667  249 1393.7168
> 66   07255               Bourges   2.350007 47.05000  161 1396.9505
> 142  07661             Cap Cepet   5.933352 43.06667  115 1402.8741
> 34   07139               Alencon   0.100002 48.43334  145 1404.6169
> 94   07475   St-Etienne Boutheon   4.283339 45.51668  404 1413.4740
> 67   07257                 Avord   2.633346 47.05000  177 1415.9491
> 144  07667                Hyeres   6.133336 43.08333    4 1423.4311
> 35   07140            Chateaudun   1.366674 48.05000  132 1430.8356
> 68   07260                Nevers   3.100002 46.98335  183 1442.4032
> 65   07249               Orleans   1.766682 47.98335  126 1447.3894
> 8    07027                  Caen  -0.450009 49.16667   78 1457.3923
> 85   07379             Saint-Yan   4.000000 46.40001  243 1460.1101
> 145  07675                Le Luc   6.383341 43.36667   81 1463.3603
> 120  07588  St-Auban-Sur-Durance   5.983353 44.05000  459 1464.3130
> 6    07020              La Hague  -1.933352 49.71668    6 1467.6693
> 7    07024 Cherbourg / Maupertus  -1.450009 49.65001  140 1474.1177
> 36   07143              Chartres   1.500010 48.45001  155 1477.2209
> 95   07480           Lyon / Bron   4.933352 45.71668  201 1482.7460
> 98   07486 Grenoble / St. Geoirs   5.300006 45.35001  397 1487.6650
> 96   07481        Lyon / Satolas   5.066668 45.71668  250 1494.0213
> 10   07031             Deauville   0.166670 49.35001  146 1501.9994
> 86   07385                 Macon   4.783349 46.28334  222 1513.1763


I guess it might be somethig of my computer, cause you could run the function. If you have any idea on how I could solve it I would really appreciate it

**Comment by aglogowski** [comment]
Di you try to reduce number of stations as the the error says that string is to wide. 
Sometimes when you change a bit coordinates the function work better. 
What is the output when you type `sys.Date()` 
the format supposed to be as follows:
"2024-02-21"

**Comment by jbaezarh** [comment]
Yes, the format of `sys.Date()` is that one. And I also tried reducing the numer of stations and changing the coordinates, but the error keep appearing

**Comment by bczernecki** [comment]
Changes introduced in the upcoming package version. Thanks for the solution!
