### ISSUE TITLE
Better error message needed

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/climate#9]
```r
library(climate)

x <- meteo_ogimet(interval = "daily", date = c("2019-06-01", "2019-07-08"),
                  station = 22222, coords = FALSE)
#> Daily raports was genereted starting form 6 am each day. Set hour to change it 
#> [1] 22222
#> 
  |                                                                       
  |                                                                 |   0%
#> Error in if ((length(test[2, !is.na(test[2, ])]) == 6 & test[2, 5] == : argument is of length zero
```

W tej sytuacji powinien pojawić się error (lub warning, patrz niżej), że takiej stacji nie ma + podpowiedź jak znaleźć stację.

Jeszcze jest druga sytuacja:

```r
  x <- meteo_ogimet(interval = "daily", date = c("2019-06-01", "2019-07-08"),
                    station = c(12330, 22222), coords = FALSE)
```

W tym wypadku teraz dostajemy nieinformacyjny error. Zamiast tego powinny się dane dla 12330 pobrać, a następnie pojawić się warning, że takiej stacji nie ma  + podpowiedź jak znaleźć stację.

**Comment by aglogowski** [comment]
JOB DONE

**Comment by Nowosad** [comment]
@aglogowski a możemy coś zrobić z drugą sytuacją? (nie musi być na teraz)

**Comment by aglogowski** [comment]
Zostało zrobione pobiera się pierwsza stacja i potem wyskakuje błąd że druga nie istnieje i należy zmienić numer stacji i jest wskazany numer

**Comment by aglogowski** [comment]
Tera chyba dobrze

**Comment by Nowosad** [comment]
:+1: myślę, że jest lepiej. Niech @bczernecki obejrzy i zamknie issue.
