### ISSUE TITLE
Why not on CRAN anymore?

### ISSUE THREAD

**Issue by upgradedavid** [bczernecki/climate#90]
Just wanted to use your amazing package again and realized it's been removed with the following explanation:

"Archived on 2022-08-14 for repeated policy violation."

Anything we could do to get it up again?

**Comment by bczernecki** [comment]
Thanks @upgradedavid for a good word ;)
As you can see on the incoming section under the CRAN it is still pending manual inspection:

<img width="807" alt="obraz" src="https://github.com/bczernecki/climate/assets/8086055/35aedc1b-51ed-4b03-a7f6-c4511d855f13">

I think I will give a re-try in a couple of weeks or re-upload the most current version once again.
