### ISSUE TITLE
Issue with Climate R Package for Streamflow Data

### ISSUE THREAD

**Issue by alifaghfouri** [bczernecki/climate#92]
I am currently using the Climate package in R for analyzing and obtaining streamflow data across various Poland stations. Firstly, I would like to extend my gratitude for your work on this valuable tool.
While working with the package, I encountered an issue where February appears to be assigned 31 days across all streamflow stations (Please kindly see the attached photo as an example). This anomaly is affecting the accuracy of my analysis, and I am seeking your guidance on how to resolve this issue.
Could you please provide any insights or suggestions on how to correct the number of days in February? If there is an update or a patch available that addresses this problem, I would greatly appreciate it if you could point me in the right direction.
Thank you very much for your time and assistance. I look forward to your response.

![Problem](https://github.com/bczernecki/climate/assets/166242550/12381727-3624-4e2b-a239-5c234cd3cbe3)

**Comment by aglogowski** [comment]
Hydrologists measure time differently than the standard January-to-December calendar year. You can see that column is idhyy but 5 columns right you have the actual month in column mm. 
This means that you don't look at February but December

**Comment by aglogowski** [comment]
Problem solved

**Comment by bczernecki** [comment]
@aglogowski how about adding a column with "normal" date that can be used by "regular" people - not only polish hydrologists?

**Comment by hicardoso** [comment]
HI, i'm tryimg t use climate package. so i want to download data from Mozambique station it is crushing and europe and america, but when i try to do the same for africa its crushing. I tried to 67341. 

[100%] Downloaded 3306 bytes...                                           |  25%
/tmp/Rtmp6KjyIu/file367439c7392d
Warning message:
In ogimet_hourly_bp(date = date, coords = coords, station = station,  :
  Wrong station ID: 67341 You can check station ID at https://ogimet.com/display_stations.php?lang=en&tipo=AND&isyn=&oaci=&nombre=&estado=&Send=Send
