### ISSUE TITLE
Error occurs Downloading OGIMet Stations for Luxembourg

### ISSUE THREAD

**Issue by BGWKlein** [bczernecki/climate#93]
When I try to download the OGIMET Stations of Luxembourg
`climate::stations_ogimet(country = "Luxembourg")`
an error occurs. The reason is that only one station is available in Luxembourg. 

Possible solution for this problem:
[https://github.com/bczernecki/climate/blob/master/R/stations_ogimet.R](https://github.com/bczernecki/climate/blob/master/R/stations_ogimet.R)
line 90
`res1 = res[, c(1, 3, 5:7), drop = FALSE]`
instead of
`res1 = res[, c(1, 3, 5:7)]`

**Comment by bczernecki** [comment]
Thanks for the feedback! Indeed, for Luxembourg there's only 1 station and thus metadata are converted from matrix into vector. It is now addressed in https://github.com/bczernecki/climate/pull/86 and should merged onto master branch soon
