### ISSUE TITLE
Zmiana układu danych hydro od IMGW od 2023 r.

### ISSUE THREAD

**Issue by adamperz** [bczernecki/climate#99]
Niestety pobranie danych hydro z IMGW za pomocą pakietu jest niemożliwe dla roku 2023 - zmieniono układ udostępniania danych, dla wcześniejszych lat dane dzienne były w oddzielnych plikach dla każdego miesiąca roku hydrologicznego, a dla 2023 r. dane ze wszystkich miesięcy są w jednym pliku.

**Comment by Nowosad** [comment]
@bczernecki reprex:

```r
# install.packages("climate")
library(climate)
h2022 = hydro_imgw_monthly(2022)
h2023 = hydro_imgw_monthly(2023)
```

**Comment by bczernecki** [comment]
Powiedzieć, że zmiana układu w danych to tak jakby nic nie powiedzieć ;)

Zmieniono liczbę plików, ale też standard seperatora dla CSV i kodowanie pliku...
Poniżej porównanie pliku CSV po rozpakowaniu dla 2022 i 2023

```
bartosz@macbook:~/Downloads$ head -n2 codz_202*.csv
==> codz_2022_01.csv <==
" 149180020","CHA�UPKI","Odra (1)","2022","01","01",78,10.100,99.9,"11"
" 149180020","CHA�UPKI","Odra (1)","2022","01","02",84,12.100,99.9,"11"

==> codz_2023.csv <==
149180020;CHAŁUPKI;Odra (1);2023;01;01;14.200;88;99.9;11
149180020;CHAŁUPKI;Odra (1);2023;01;02;13.700;89;99.9;11
```
